// Create a clone of the rock paper scissor game. The player will give rock, paper or scissor as input and compare it with
// a random input(rock, paper or scissor) generated by the computer then both of them will be compared and it will be decided
// who won that round. +1 the score whoever wins that round (0 if tie). Display the scores of the player and cpu after each round
// 1 game will be of 5 rounds. If the score is tie after the 5 rounds then there will be unlimited tie-breaker rounds.

package Exercises.All_Coding_Exercises.Medium;

import java.util.Random;
import java.util.Scanner;

public class q018_RockPaperScissorClone {
    // creating a function which will randomly generate rock, paper or scissor
    static String computerResponse() {
        // generating a random number
        Random random = new Random();
        int randomNumber = random.nextInt(1, 4); // generate either 1 or 2 or 3
        if (randomNumber == 1) {
            return "Rock";
        } else if (randomNumber == 2) {
            return "Paper";
        } else {
            return "Scissor";
        }
    }

    // Creating a function which will compare the user input with the computerResponse
    static String compareInputs(String userInput, String computerResponse) {
        if (userInput.equalsIgnoreCase("rock") && computerResponse.equalsIgnoreCase("paper") ||
                userInput.equalsIgnoreCase("paper") && computerResponse.equalsIgnoreCase("scissor") ||
                userInput.equalsIgnoreCase("scissor") && computerResponse.equalsIgnoreCase("rock")) {
            return ("You entered " + userInput + " and the computer entered " + computerResponse + ". The computer WON !!!");
        } else if (userInput.equalsIgnoreCase("paper") && computerResponse.equalsIgnoreCase("rock") ||
                userInput.equalsIgnoreCase("scissor") && computerResponse.equalsIgnoreCase("paper") ||
                userInput.equalsIgnoreCase("rock") && computerResponse.equalsIgnoreCase("scissor")) {
            return ("You entered " + userInput + " and the computer entered " + computerResponse + ". You WON !!!");
        } else {
            return ("You entered " + userInput + " and the computer entered " + computerResponse + ". It's a tie.");
        }
    }

    // Creating a function to display the final result
    static void finalResult(int userScore, int computerScore) {
        if (userScore > computerScore) {
            System.out.println("YOU WON THE GAME !!!!!! 😊😁");
        } else if (computerScore > userScore) {
            System.out.println("YOU LOST THE GAME 😓😭");
        }
    }

    public static void main(String[] args) {
        System.out.println("This is a program where you play Rock Paper Scissor against the computer.");
        System.out.println("This game will be of 5 rounds.");
        int userScore = 0;
        int computerScore = 0;
        Scanner scanner = new Scanner(System.in);
        for (int i = 0; i < 5; i++) {
            System.out.println("Enter the input (Rock, Paper or Scissor) : ");
            String userInput = scanner.next();
            String result = compareInputs(userInput, computerResponse());
            if (result.contains("You WON")) {
                userScore++;
            } else if (result.contains("computer WON")) {
                computerScore++;
            }
            System.out.println(result);
            System.out.println("The score is : ");
            System.out.println("CPU : " + computerScore + "          YOU : " + userScore);
        }
        finalResult(userScore, computerScore);
        while (userScore == computerScore) {
            System.out.println("This is a TIE BREAKER round.");
            System.out.println("Enter the input (Rock, Paper or Scissor) : ");
            String userInput = scanner.next();
            String result = compareInputs(userInput, computerResponse());
            if (result.contains("You WON")) {
                userScore++;
            } else if (result.contains("computer WON")) {
                computerScore++;
            }
            System.out.println(result);
            System.out.println("The score is : ");
            System.out.println("CPU : " + computerScore + "          YOU : " + userScore);
            finalResult(userScore, computerScore);
        }
        scanner.close();
    }
}
